# Generated by Django 4.2 on 2026-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virement_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedxml',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
