# Generated by Django 4.2 on 2026-03-19 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virement_app', '0003_generatedxml_recipient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedxml',
            name='recipient_email',
        ),
        migrations.AddField(
            model_name='generatedxml',
            name='purpose_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generatedxml',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generatedxml',
            name='transaction_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generated_xml', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virement_app.generatedxml')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
