# Generated by Django 4.2 on 2026-03-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virement_app', '0004_remove_generatedxml_recipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedxml',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='excel_files/'),
        ),
    ]
