# Generated by Django 4.2 on 2026-03-26 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virement_app', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='Peut gérer les utilisateurs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_all_files',
            field=models.BooleanField(default=False, verbose_name='Peut voir tous les fichiers'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_users',
            field=models.ManyToManyField(blank=True, related_name='viewed_by_comptables', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs dont il peut voir les fichiers'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('comptable', 'Comptable'), ('user', 'Utilisateur')], default='user', max_length=20, verbose_name='Rôle'),
        ),
    ]
