# Generated by Django 4.2.7 on 2026-09-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virement_app', '0008_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generatedxml',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('comptable', 'Comptable'), ('user', 'Utilisateur'), ('user_xml_verifier', 'Vérificateur XML')], default='user', max_length=40, verbose_name='Rôle'),
        ),
    ]
